### ISSUE TITLE
Логическая ошибка в операции пополнения кредитной карты

### ISSUE THREAD

**Issue by AndreyTu** [AndreyTu/javaqa-team-diplom-2#1]
# Описание 
При пополнение счета (amount) на число, больше 0, баланс (balance) всегда равен сумме пополнения. 

# Локация дефекта
```java
    @Override
    public boolean add(int amount) {
        if (amount <= 0) {
            return false;
        }
        balance = amount;
        return true;
    }
```
https://github.com/AndreyTu/javaqa-team-diplom-2/blob/10d7b7caff7ccb3388f72764a5c63511555d4fb7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L64C1-L71C6

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L64C1-L71C6) в IDEA

2. Перейти в тестовый класс CreditAccountTest

3. Создать тест пополнения кредитной карты - shouldAddToPositiveBalance

4. Создать объект класса CreditAccount и внести начальные данные :
```java
initialBalance = 2_000
creditLimit  = 5_000
rate = 15
```
5. Вызвать метод пополнения кредитной карты add на сумму 3_000.

6. Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : Balance - 5_000 руб
Фактический результат : Balance - 3_000 руб

# Тест
```java
    @Test
    public void shouldAddToPositiveBalance() {
        CreditAccount account = new CreditAccount(
                2_000,
                5_000,
                15
        );
        account.add(3_000);
        Assertions.assertEquals(3_000, account.getBalance());
```
  https://github.com/AndreyTu/javaqa-team-diplom-2/blob/10d7b7caff7ccb3388f72764a5c63511555d4fb7/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L8C5-L18C62

# Скриншот

![Screenshot_4](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/139591226/d1f82ef0-4423-43c0-a17d-ff2c41a87700)

# Окружение 

Windows 10 Pro
IntelliJ IDEA Community Edition 2023.1.4
JAVA : OpenJDK11

**Comment by Sergey30ssw** [comment]
# Способ решения:
В методе `add()` класса `CreditAccount` равенство `balance = amount` исправить на: `balance = balance + amount`. 

# Шаги решения:
1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/10d7b7caff7ccb3388f72764a5c63511555d4fb7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L64C1-L71C6) в IDEA.
2. Перейти в класс `CreditAccount`.
3. В методе `add()` класса `CreditAccount` равенство `balance = amount` исправить на: `balance = balance + amount`. 
4. Запустить повторно тест и убедиться в его успешном завершении (Process finished with exit code 0).

# Тест:
@Test
public void shouldAddToPositiveBalance() {
    CreditAccount account = new CreditAccount(
            2_000,
            5_000,
            15
    );
    account.add(3_000);
    Assertions.assertEquals(5_000, account.getBalance());
}

# Скриншот:
![image](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/133129423/e37c510c-5001-439e-8cdd-596d810647ec)


**Ожидаемый результат:** Balance - 5_000 руб.
**Фактический результат:** Balance - 5_000 руб.
