### ISSUE TITLE
Параметр creditLimit не имеет исключения на отрицательное значение

### ISSUE THREAD

**Issue by AndreyTu** [AndreyTu/javaqa-team-diplom-2#10]
# Описание
Отсутствует проверка параметра кредитный лимит на предмет ошибочного ввода отрицательного значения.
https://github.com/AndreyTu/javaqa-team-diplom-2/blob/10d7b7caff7ccb3388f72764a5c63511555d4fb7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L16

# Локация дефекта
```java
public CreditAccount(int initialBalance, int creditLimit, int rate) {
        if (rate <= 0) {
            throw new IllegalArgumentException(
                    "Накопительная ставка не может быть отрицательной, а у вас: " + rate
            );
        }
        this.balance = initialBalance;
        this.creditLimit = creditLimit;
        this.rate = rate;
    }
```
https://github.com/AndreyTu/javaqa-team-diplom-2/blob/10d7b7caff7ccb3388f72764a5c63511555d4fb7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA

2. Перейти в тестовый класс CreditAccountTest

3. Создать тест проверки операции пополнения кредитной карты - testIllegalArgumentExceptionCreditLimit

4. Создать объект класса CreditAccount

5. Написать проверку на появление исключения IllegalArgumentException, в случает отрицательного CreditLimit.

6. Передать в строке Assertions объект класса CreditAccount с заполненными полями:
```java
initialBalance (начальный баланс) =5_000
creditLimit (кредитный лимит) = -10_000
rate (ставка) = 10
```
7. Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат :  true
Фактический результат : false

# Тест

```java
@Test 
 public void testIllegalArgumentExceptionCreditLimit() { 
  
     Assertions.assertThrows(IllegalArgumentException.class, () -> {new CreditAccount(5000, -10000, 10);}); 
 } 
```

# Скриншот

![Screenshot_15](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/139591226/3d9cff93-0c98-4375-9be0-6ff03bd9c67d)

# Окружение 

Windows 10 Pro
IntelliJ IDEA Community Edition 2023.1.4
JAVA : OpenJDK11

**Comment by Sergey30ssw** [comment]
# Способ решения:
В классе `CreditAccount` добавить исключение на ввод некорректного значения кредитного лимита.

# Шаги решения:
1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2. Перейти в класс `CreditAccount`.
3. Добавить исключение в виде:
if (creditLimit < 0) {
throw new IllegalArgumentException(
"Кредитный лимит не может быть отрицательным, а у вас: " + creditLimit
);
}
4. Перейти в тестовый класс `CreditAccountTest`
5. Запустить тест `testIllegalArgumentExceptionCreditLimit`.

# Тест:
@Test
    public void testIllegalArgumentExceptionCreditLimit() {

        Assertions.assertThrows(IllegalArgumentException.class, () -> {
            new CreditAccount(5_000, -10_000, 10);
        });
    }
# Скриншот:
![image](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/133129423/7374a097-d3db-4217-a1ef-92acf05c5c1c)

**Ожидаемый результат:** проверка параметра кредитного лимита на предмет ошибочного ввода отрицательного значения прошла успешно - тест успешно завершен (Process finished with exit code 0).
**Фактический результат:** проверка параметра кредитного лимита на предмет ошибочного ввода отрицательного значения прошла успешно - тест успешно завершен (Process finished with exit code 0).
