### ISSUE TITLE
Не выдается исключение при начальном балансе больше максимального

### ISSUE THREAD

**Issue by Sergey30ssw** [AndreyTu/javaqa-team-diplom-2#12]
**Описание**
При создании объекта класса SavingAccount с некорректными параметрами, где начальный баланс больше максимального, не выдается исключение IllegalArgumentException несмотря на то, что данный вид параметров должен вызывать исключение.

**Локация дефекта**
https://github.com/netology-code/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32
Lines 22 to 32 

 public SavingAccount(int initialBalance, int minBalance, int maxBalance, int rate) { 
     if (rate < 0) { 
         throw new IllegalArgumentException( 
           "Накопительная ставка не может быть отрицательной, а у вас: " + rate 
         ); 
     } 
     this.balance = initialBalance; 
     this.minBalance = minBalance; 
     this.maxBalance = maxBalance; 
     this.rate = rate; 
 } 

**Шаги воспроизведения:**

1. Открыть [код программы](https://github.com/netology-code/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2. Создать объект класса `SavingAccoun`t с параметрами: `initialBalance = 15_000`,` minBalance = 1_000`, `maxBalance = 10_000`, `rate = 5`.
3. Создать тест для проверки выдачи исключения при начальном балансе больше максимального.

_Ожидаемый результат:_ при создании объекта должно выдаваться исключение `IllegalArgumentException` с соответствующим сообщением о некорректных параметрах.

_Фактический результат:_ исключение `IllegalArgumentException` не выдается, и объект создается без ошибок.

**Тест:**
@Test
    public void testIllegalArgumentExceptionInitialBalanceMoreMaxBalance (){
        Assertions.assertThrows(IllegalArgumentException.class, () -> new SavingAccount(15_000,1_000,10_000,5));
    }

**Скриншот**
![image](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/133129423/ce70a281-2283-41d1-855a-5502f05df19a)

**Окружение**

- **Операционная система:** Windows 10 Pro v. 21H2
- **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
- **JAVA:** OpenJDK 11

**Comment by AndreyTu** [comment]
# Способ решения
Внесение изменений в код класса SavingAccount

# Шаги решения
1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom) в IDEA

2. Перейти в класс SavingAccount

3. Внести изменения в метод: SavingAccount

```java
public SavingAccount(int initialBalance, int minBalance, int maxBalance, int rate) {
        if (rate < 0) {
            throw new IllegalArgumentException(
                    "Накопительная ставка не может быть отрицательной, а у вас: " + rate
            );
        }
        if (minBalance < 0) {
            throw new IllegalArgumentException(
                    "Минимальный баланс не может быть отрицательной, а у вас: " + minBalance
            );
        }
        if (initialBalance < 0) {
            throw new IllegalArgumentException(
                    "Первоначальный баланс не может быть меньше нуля, а у вас: " + initialBalance
            );
        }
        if ((initialBalance < minBalance) || (initialBalance > maxBalance)) {
            throw new IllegalArgumentException(
                    "Первоначальный баланс должен быть в пределах от минимального до максимального значения включительно, а у вас: " + initialBalance
            );
        }
        if (minBalance > maxBalance) {
            throw new IllegalArgumentException(
                    "Минимальный баланс не может быть больше максимального баланса, а у вас: " + minBalance
            );
        }

        this.balance = initialBalance;
        this.minBalance = minBalance;
        this.maxBalance = maxBalance;
        this.rate = rate;
    }
```

5. Перейти в тестовый класс SavingAccountTest
6. Запустить с прежними данными тест: testIllegalArgumentExceptionInitialBalanceMoreMaxBalance

![Screenshot_7](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/139591226/184168e1-823c-407a-986f-58bf1107da25)


**Ожидаемый результат** : при создании объекта должно выдаваться исключение IllegalArgumentException с соответствующим сообщением о некорректных параметрах.
**Фактический результат** : Тест проходит успешно Process finished with exit code 0
