### ISSUE TITLE
Не происходит пополнение счета при достижении максимального значения баланса в методе add (int amount)

### ISSUE THREAD

**Issue by Sergey30ssw** [AndreyTu/javaqa-team-diplom-2#13]
**Описание**
В методе add(int amount) класса SavingAccount обнаружена ошибка, которая приводит к отсутствию возможности пополнения счета при достижении максимального значения.

**Локация дефекта**

https://github.com/netology-code/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72

 if (balance + amount < maxBalance) { 

**Шаги воспроизведения:**
1. Создать экземпляр класса `SavingAccount` с начальным балансом `2_000`, минимальным балансом `1_000`, максимальным балансом `10_000` и ставкой `5`.
2. Вызвать метод `add(int amount)` с заданной суммой пополнения `8_000`.
3. Проверить результат пополнения счета и значение баланса счета.

_Ожидаемый результат:_ баланс счета должен быть увеличен до максимального значения `10_000` после пополнения счета.

Фактический результат: баланс счета остается равным `2_000`, пополнение счета не происходит при достижении максимального значения.

Тест
@Test
    public void shouldAddEqualsMaxBalance() {
        SavingAccount account = new SavingAccount(
                2_000,
                1_000,
                10_000,
                5
        );

        account.add(8_000);

        Assertions.assertEquals(2_000 + 8_000, account.getBalance());
    }

**Скриншот**
![image](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/133129423/fbeacfa8-90be-4eb3-9e61-c8e858765b18)

**Окружение**

- **Операционная система:** Windows 10 Pro v. 21H2
- **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
- **JAVA:** OpenJDK 11

**Comment by AndreyTu** [comment]
# Способ решения
Внесение изменений в код класса SavingAccount

# Шаги решения
1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom) в IDEA

2. Перейти в класс SavingAccount

3. Внести изменения в метод: add
```java
@Override
    public boolean add(int amount) {
        if (amount <= 0) {
            return false;
        }
        if ((balance + amount) <= maxBalance) {
            balance += amount;
            return true;
        } else {
            return false;
        }
    }
```

5. Перейти в тестовый класс SavingAccountTest
6. Запустить с прежними данными тест: shouldAddEqualsMaxBalance

![Screenshot_4](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/139591226/57a08853-66ad-41db-ae25-2aac2a678b48)



**Ожидаемый результат** : баланс счета должен быть увеличен до максимального значения 10_000 после пополнения счета.

Фактически
**Фактический результат** :  баланс счета должен быть увеличен до максимального значения 10_000 после пополнения счета. (  Process finished with exit code 0 ).
