### ISSUE TITLE
Равенство creditLimit и balance приводит к ошибке в методе pay

### ISSUE THREAD

**Issue by AndreyTu** [AndreyTu/javaqa-team-diplom-2#14]
# Описание
При условии, когда баланс , после применения метода pay, будет равен кредитному лимиту, метод pay возвращает false. 

# Локация дефекта

```java
    @Override
    public boolean pay(int amount) {
        if (amount <= 0) {
            return false;
        }
        balance = balance - amount;
        if (balance > -creditLimit) {
            balance = -amount;
            return true;
        } else {
            return false;
        }
    }
```
https://github.com/AndreyTu/javaqa-team-diplom-2/blob/10d7b7caff7ccb3388f72764a5c63511555d4fb7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L39C2-L51C6

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA

2. Перейти в тестовый класс CreditAccountTest

3. Создать тест проверки операции пополнения кредитной карты - testPayBalanceEqualsCreditLimit

4. Создать объект класса CreditAccount и внести начальные данные :

```java
initialBalance (начальный баланс) = 5_000
creditLimit (кредитный лимит) = 10_000
rate (ставка) = 10
```
5. Вызвать метод покупки по карте - pay на сумму 15000 руб.
6. Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат :  true
Фактический результат : false

# Тест

```java
@Test 
 public void testPayBalanceEqualsCreditLimit() {
     CreditAccount account = new CreditAccount(5_000, 10_000, 10); 
  
     boolean expected = true;
     boolean actual = account.pay(15_000); 
  
     Assertions.assertEquals(expected, actual); 
 } 
```

# Скриншот

![Screenshot_19](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/139591226/e797d4b2-435f-4788-a7f0-9580cab109dd)

# Окружение 

Windows 10 Pro
IntelliJ IDEA Community Edition 2023.1.4
JAVA : OpenJDK11

**Comment by Sergey30ssw** [comment]
# Способ решения:
Решено в Issue #3 и Issue #4.

# Шаги решения:
Аналогичны шагам в Issue #3 и Issue #4.

# Тест:
@Test
    public void testPayBalanceEqualsCreditLimit() {
        CreditAccount account = new CreditAccount(5_000, 10_000, 10);

        boolean expected = true;
        boolean actual = account.pay(15_000);

        Assertions.assertEquals(expected, actual);
    }

# Скриншот:
![image](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/133129423/0e715412-8177-4f2a-95a7-984dffaaa915)

**Ожидаемый результат:** true (Process finished with exit code 0).
**Фактический результат:** true (Process finished with exit code 0).
