### ISSUE TITLE
Начисление процентов на положительный баланс кредитной карты

### ISSUE THREAD

**Issue by AndreyTu** [AndreyTu/javaqa-team-diplom-2#17]
# Описание
Метод начисления процентов на  баланс кредитной карты yearChange

# Локация дефекта

     * Пример 2: если на счёте 200 рублей, то при любой ставке ответ должен быть 0.

```java
public int yearChange() { 
     return balance / 100 * rate; 
 } 
```

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/tree/main/src/test/java/ru/netology/javaqadiplom) в IDEA

2. Перейти в тестовый класс CreditAccountTest

3. Создать тест проверки yearChange

4. Создать объект класса CreditAccount и внести начальные данные :

```java
initialBalance  = 5_000
creditLimit  = 5_000
rate (ставка) = 10
```
5. Вызвать метод 
6. Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : 0,   Process finished with exit code 0
Фактический результат : 500

# Тест

```java
@Test
    public void testYearChangePositiveBalance() {
        CreditAccount account = new CreditAccount(5_000, 5_000, 10);

        int expected = 0;
        int actual = account.yearChange();

        Assertions.assertEquals(expected, actual);
    }
```

# Скриншот

![Screenshot_5](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/139591226/c8f0c01d-0b13-4812-b0ac-7e10dfd7c22c)

# Окружение 

Windows 10 Pro
IntelliJ IDEA Community Edition 2023.1.4
JAVA : OpenJDK11

**Comment by Sergey30ssw** [comment]
# Способ решения:
Внести изменения в исходный код, добавив строку: if (balance >= -creditLimit && balance<0):
@Override
    public int yearChange() {
        if (balance >= -creditLimit && balance < 0) {
            return balance / 100 * rate;
        }
        return 0;
    }  
# Шаги решения:
1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
2. Внести изменения в исходный код, добавив условие проверки:
@Override
    public int yearChange() {
        if (balance >= -creditLimit && balance < 0) {
            return balance / 100 * rate;
        }
        return 0;
    }
3. Перейти в тестовый класс `CreditAccountTest`.
4. Запустить тест начисления процентов: ` testYearChangePositiveBalance` и убедиться в его успешном завершении (Process finished with exit code 0).

# Тест:
@Test
    public void testYearChangePositiveBalance() {
        CreditAccount account = new CreditAccount(5_000, 5_000, 10);

        int expected = 0;
        int actual = account.yearChange();

        Assertions.assertEquals(expected, actual);
    }

# Скриншот:
![image](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/133129423/82d50d05-0c0c-453a-8290-dd3e97f61671).

_Ожидаемый результат:_ Тест успешно завершен (Process finished with exit code 0).
_Фактический результат:_ Тест успешно завершен (Process finished with exit code 0).
