### ISSUE TITLE
На отрицательный баланс сберегательного счета происходит начисление процентов

### ISSUE THREAD

**Issue by Sergey30ssw** [AndreyTu/javaqa-team-diplom-2#18]
# Описание:
Метод начисления процентов на положительный баланс сберегательного счета yearChange начисляет проценты в случае отрицательного баланса сберегательного счета

# Локация дефекта:
[javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java](https://github.com/netology-code/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L87-L90)

 @Override 
 public int yearChange() { 
     return balance / 100 * rate; 
 } 
# Шаги воспроизведения:
1. Открыть [код программы](https://github.com/netology-code/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L87-L90) в IDEA.
2. Перейти в тестовый класс `SavingAccountTest`.
3. Создать тест проверки операции начисления процентов на остаток баланса - `shouldYearChangeOnNegativeBalance`.
4. Создать объект класса `SavingAccount` и внести начальные данные :
initialBalance (начальный баланс) = -100
minBalance (минимальный баланс) = 0
maxBalance (максимальный баланс) = 10_000
rate (ставка) = 15
5. Запустить тест, посмотреть результат теста в консоли.

# Тест:

     @Test 
     public void shouldYearChangeOnNegativeBalance() { 
         SavingAccount account = new SavingAccount( 
                 -100, 
                 0, 
                 10_000, 
                 15 
         ); 
           account.yearChange(); 
           Assertions.assertEquals(0, account.yearChange()); 
     } 
 } 

_Ожидаемый результат:_ Начислено 0.
_Фактический результат :_ Начислено -15.

# Скриншот:
![image](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/133129423/714797f5-c7f7-43d2-8ad2-cca80a05c5cc)

# Окружение:
- **Операционная система:** Windows 10 Pro v. 21H2
- **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
- **JAVA:** OpenJDK 11

**Comment by AndreyTu** [comment]
# Способ решения
Внесение изменений в код класса SavingAccount

# Шаги решения
1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom) в IDEA

2. Перейти в класс SavingAccount

3. Внести изменения в метод: 
```java
 @Override
    public int yearChange() {
        if (balance > minBalance) {
            return balance / 100 * rate;
        } else {
            return 0;
        }
    }

    public int getMinBalance() {

        return minBalance;
    }

    public int getMaxBalance() {

        return maxBalance;
    }
```

5. Перейти в тестовый класс SavingAccountTest
6. Запустить с прежними данными тест: shouldYearChangeOnNegativeBalance



**Ожидаемый результат** : Первоначальный баланс не может быть меньше нуля, а у вас: -100

Фактически
**Фактический результат** : Первоначальный баланс не может быть меньше нуля, а у вас: -100
