### ISSUE TITLE
Начисление процентов на негативный баланс кредитной карты

### ISSUE THREAD

**Issue by AndreyTu** [AndreyTu/javaqa-team-diplom-2#2]
# Описание

Метод yearChange неверно начисляет проценты на негативный баланс кредитной карты .

# Локация дефекта
```java
    @Override
    public int yearChange() {
        return balance / 100 * rate;
    }
```
https://github.com/AndreyTu/javaqa-team-diplom-2/blob/10d7b7caff7ccb3388f72764a5c63511555d4fb7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L81C1-L84C6

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA

2. Перейти в тестовый класс CreditAccountTest

3. Создать тест проверки операции пополнения кредитной карты - testYearChangeNegativeBalance

4. Создать объект класса CreditAccount и внести начальные данные :
```java
initialBalance = -4_000
creditLimit = 5_000
rate  = 10
```
5. Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : Проценты - 0 руб
Фактический результат : Проценты - (-400) руб

# Тест
```java
    @Test
    public void testYearChangeNegativeBalance() {
        CreditAccount account = new CreditAccount(
                -4_000,
                5_000,
                10);

        int expected = 0;
        int actual = account.yearChange();

        Assertions.assertEquals(expected, actual);
    }
```
https://github.com/AndreyTu/javaqa-team-diplom-2/blob/1be354415a1be7dc54285f4ffd1686390b19577e/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L21C5-L33C6

# Скриншот

![Screenshot_11](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/139591226/87a084c1-d473-42b1-b195-c84c568b010c)

# Окружение 

Windows 10 Pro
IntelliJ IDEA Community Edition 2023.1.4
JAVA : OpenJDK11

**Comment by Sergey30ssw** [comment]
# Способ решения:
1. Внести изменения в исходный код, добавив строку: if (balance >= -creditLimit && balance<0):
@Override
    public int yearChange() {
        if (balance >= -creditLimit && balance < 0) {
            return balance / 100 * rate;
        }
        return 0;
    }  
# Шаги решения:
1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L98) в IDEA.
2. Внести изменения в исходный код, добавив условие проверки:
@Override
    public int yearChange() {
        if (balance >= -creditLimit && balance < 0) {
            return balance / 100 * rate;
        }
        return 0;
    } 
3. Перейти в тестовый класс `CreditAccountTest`.
4. Запустить тест операции пополнения кредитной карты -` YearChangeNegativeBalance` и убедиться в его успешном завершении (Process finished with exit code 0).

# Тест:
@Test
    public void yearChangeNegativeBalance() {
        CreditAccount account = new CreditAccount(1_000, 6_000, 10);

        account.pay(2000);
        int expected = -100;
        int actual = account.yearChange();

        Assertions.assertEquals(expected, actual);
    }
# Скриншот:
![image](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/133129423/9d20b95f-2267-4c8e-9253-4584ebaaa152)

*Ожидаемый результат:* Проценты - 0 руб.
*Фактический результат:* Проценты - 0 руб.

**Comment by AndreyTu** [comment]
Тест удален
