### ISSUE TITLE
Метод добавления (add) на счет при отрицательном балансе 

### ISSUE THREAD

**Issue by AndreyTu** [AndreyTu/javaqa-team-diplom-2#3]
# Описание
Метод начисления денежных средств на счет при отрицательном балансе работает не корректно. 

# Локация дефекта
       
```java
        @Override
    public boolean add(int amount) {
        if (amount <= 0) {
            return false;
        }
        balance = amount;
        return true;
    }
```
https://github.com/AndreyTu/javaqa-team-diplom-2/blob/10d7b7caff7ccb3388f72764a5c63511555d4fb7/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L39C4-L51C6

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L64C1-L71C6) в IDEA

2. Перейти в тестовый класс CreditAccountTest

3. Создать тест проверки операции пополнения кредитной карты - shouldAddToNegativeBalance

4. Создать объект класса CreditAccount и внести начальные данные :
```java
initialBalance  = -2_000
creditLimit  = 5_000
rate = 15
```
5. Вызвать метод add на карту - pay на сумму 3000 руб.

6. Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат : баланс - 1000 руб
Фактический результат : баланс - (3000) руб

# Тест
```java
    @Test
    public void shouldAddToNegativeBalance() {
        CreditAccount account = new CreditAccount(
                -2_000,
                5_000,
                15
        );

        account.add(3_000);

        Assertions.assertEquals(1_000, account.getBalance());
    }
}
```
https://github.com/AndreyTu/javaqa-team-diplom-2/blob/1be354415a1be7dc54285f4ffd1686390b19577e/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L50C5-L62C2

# Скриншот

![Screenshot_13](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/139591226/c36d8218-5cb0-4c28-b645-23c723ea9cc7)

# Окружение 

Windows 10 Pro
IntelliJ IDEA Community Edition 2023.1.4
JAVA : OpenJDK11

**Comment by Sergey30ssw** [comment]
# Способ решения:
В классе `CreditAccount` в методе `pay`  условие `balance = balance - amount` вставить после проверки баланса, а строку `balance = -amount` удалить. Также изменить условие на: `if (balance - amount >= -creditLimit)`. Вставить исключение "Начальный баланс не может быть отрицательным", создать тест проверки данного исключения.

# Шаги решения:
1. Открыть [код](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L64C1-L71C6) в IDEA.
2. Перейти в класс `CreditAccount`.
3. Внести изменения в код:

@Override
    public boolean pay(int amount) {
        if (amount <= 0) {
            return false;
        }

        if (balance - amount >= -creditLimit) {
            balance = balance - amount;
            return true;
        } else {
            return false;
        }
    }
4. Вставить исключение:
if (initialBalance < 0) {
            throw new IllegalArgumentException(
                    "Начальный баланс не может быть отрицательным, а у вас: " + initialBalance
            );
5. Ввиду того, что предложенный Андреем (AndreyTu) тест после добавления завершается с результатом -1: "Начальный баланс не может быть отрицательным, а у вас: " + initialBalance", запустить тест проверки изменения и исключения - п. 4, проверить результат в консоли.

# Тест:
@Test
    public void testIllegalArgumentExceptionInitialBalance() {

        Assertions.assertThrows(IllegalArgumentException.class, () -> {
            new CreditAccount(-5_000, 10_000, 10);
        });
    }

# Скриншот:
![image](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/133129423/265f4e0a-ad25-4cf1-a5b7-6f6cf78afb1d)

_Ожидаемый результат:_ Ошибка исправлена, тест успешно завершен (Process finished with exit code 0).
_Фактический результат:_ Ошибка исправлена, тест успешно завершен (Process finished with exit code 0).

**Comment by AndreyTu** [comment]
Тест удален
