### ISSUE TITLE
Платеж свыше кредитного лимита

### ISSUE THREAD

**Issue by AndreyTu** [AndreyTu/javaqa-team-diplom-2#4]
# Описание

При методе платежа, свыше суммы баланса и кридитного лимита выдает не корректный расчет.

# Локация дефекта
```java
    @Override
    public boolean pay(int amount) {
        if (amount <= 0) {
            return false;
        }
        balance = balance - amount;
        if (balance > -creditLimit) {
            balance = -amount;
            return true;
        } else {
            return false;
        }
    }
```
https://github.com/AndreyTu/javaqa-team-diplom-2/blob/1be354415a1be7dc54285f4ffd1686390b19577e/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L35C5-L48C6

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA

2. Перейти в тестовый класс CreditAccountTest

3. Создать тест проверкикредитной карты - testPayOverCreditLimitBalance

4. Создать объект класса CreditAccount и внести начальные данные :
```java
initialBalance = 2_000
creditLimit = 5_000
rate = 10
```
5. Вызвать метод покупки по карте - pay на сумму 10000 руб.

6. Запустить тест, посмотреть результат теста в консоли.

Ожидаемый результат :  баланс - 2000 руб
Фактический результат : баланс - (-8000) руб

# Тест
```java
    @Test
    public void testPayOverCreditLimitBalance() {
        CreditAccount account = new CreditAccount(
                2000,
                5_000,
                10
        );

        account.pay(10_000);

        int expected = 2000;

        Assertions.assertEquals(expected, account.getBalance());
    }
```
https://github.com/AndreyTu/javaqa-team-diplom-2/blob/1be354415a1be7dc54285f4ffd1686390b19577e/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L35C5-L48C6

# Скриншот

![Screenshot_12](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/139591226/456ba0b5-fed3-49da-8b10-e0a392266414)

# Окружение 

Windows 10 Pro
IntelliJ IDEA Community Edition 2023.1.4
JAVA : OpenJDK11

**Comment by Sergey30ssw** [comment]
# Способ решения:

Проверить работоспособность изменений, внесенных ранее в исходный код (см. Issue #3)

# Шаги решения:
1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L64C1-L71C6) в IDEA.
2. Проверить внесенные в Issue #3 изменения в исходный код.
3. Перейти в тестовый класс `CreditAccountTest`.
4. Запустить тест  -` PayOverCreditLimitBalance` и убедиться в его успешном завершении (Process finished with exit code 0).

# Тест:
@Test
    public void PayOverCreditLimitBalance() {
        CreditAccount account = new CreditAccount(
                2000,
                5_000,
                10
        );

        account.pay(10_000);

        int expected = 2000;

        Assertions.assertEquals(expected, account.getBalance());
    }
# Скриншот:
![image](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/133129423/169670de-1c7c-45a4-ad93-d2d272f24de9)

*Ожидаемый результат:* Ошибок не выявлено (Process finished with exit code 0).
*Фактический результат:* Ошибок не выявлено (Process finished with exit code 0).
