### ISSUE TITLE
Присваивание значения суммы пополнения вместо увеличения баланса в методе add(int amount)

### ISSUE THREAD

**Issue by Sergey30ssw** [AndreyTu/javaqa-team-diplom-2#5]
**Описание**
В методе add(int amount) класса SavingAccount обнаружена ошибка в логике. Вместо увеличения баланса на сумму пополнения происходит присваивание значения суммы пополнения самому балансу. Это приводит к неправильному результату: баланс счета становится равным сумме пополнения, а не увеличивается на эту сумму.

**Локация дефекта**
[javaqa-team-diplom-2/src/main/java/ru/netology/javaqadiplom/SavingAccount.java](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L73)

 balance = amount; 
**Шаги воспроизведения**
1. Создать экземпляр класса `SavingAccount` с начальным балансом `2_000`, минимальным балансом `1_000`, максимальным балансом `10_000` и ставкой `5`.
2. Вызвать метод `add(int amount)` с заданной суммой пополнения `3_000`.
3. Проверить результат пополнения счета и значение баланса счета.

_Ожидаемый результат:_ метод `add(int amount)` должен увеличить баланс счета на заданную сумму пополнения. Значение баланса счета после пополнения должно быть равно `5_000`.

_Фактический результат:_ вместо увеличения баланса на сумму пополнения счета присваивается значение суммы пополнения самому балансу. Это приводит к неправильному значению баланса, которое становится равным `3_000`.

Тест
[javaqa-team-diplom-2/blob/main/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L8-L20)

 @Test 
 public void shouldAddLessThanMaxBalance() { 
     SavingAccount account = new SavingAccount( 
             2_000, 
             1_000, 
             10_000, 
             5 
     ); 
  
     account.add(3_000); 
  
     Assertions.assertEquals(2_000 + 3_000, account.getBalance()); 
 } 

**Скриншот**
![image](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/133129423/7faaf84c-390a-4c35-a5b6-c63bfe20a207)

**Окружение**

- **Операционная система:** Windows 10 Pro v. 21H2
- **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
- **JAVA:** OpenJDK 11

**Comment by AndreyTu** [comment]
# Способ решения
Внесение изменений в код класса SavingAccountTest

# Шаги решения
1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom) в IDEA

2. Перейти в класс SavingAccount

3. Внести изменения в конструктор класса: 
```java
@Override
    public boolean add(int amount) {
        if (amount <= 0) {
            return false;
        }
        if ((balance + amount) <= maxBalance) {
            balance += amount;
            return true;
        } else {
            return false;
        }
    }
```

5. Перейти в тестовый класс SavingAccountTest
6. Запустить с прежними данными тест shouldAddLessThanMaxBalance



**Ожидаемый результат** : 5_000
**Фактический результат** : 5_000 (Process finished with exit code 0)
