### ISSUE TITLE
Отрицательный баланс при выполнении операции оплаты в методе pay(int amount)

### ISSUE THREAD

**Issue by Sergey30ssw** [AndreyTu/javaqa-team-diplom-2#6]
**Описание**
В методе `pay(int amount)` класса `SavingAccount` происходит вычитание суммы покупки из баланса счета без проверки на отрицательный баланс

**Локация дефекта**
https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L48

 balance = balance - amount; 

**Шаги воспроизведения**
1. Создать экземпляр класса `SavingAccount` с начальным балансом `1_000`, минимальным балансом `1_000`, максимальным балансом `10_000` и ставкой `5`.
2. Вызвать метод pay(int amount) с заданной суммой покупки `3_000`.
3. Проверить результат уменьшения счета и значение баланса счета.

_Ожидаемый результат:_ Метод pay должен вернуть false, баланс счета должен остаться без изменений, равный 1_000

_Фактический результат:_ Метод `pay` возвращает `true`, что указывает на успешное выполнение операции, несмотря на отрицательный баланс равный `-2000`.

Тест
@Test
    public void shouldNotPayBeyondBalance() {
        SavingAccount account = new SavingAccount(
                1_000,
                1_000,
                10_000,
                5
        );

        boolean result = account.pay(3_000);

        Assertions.assertFalse(result);
        Assertions.assertEquals(1_000, account.getBalance());
    }

**Скриншот:**
![image](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/133129423/bd1f60e1-1998-48dc-9a60-13ae280795ca)

**Окружение:**
- **Операционная система:** Windows 10 Pro v. 21H2
- **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
- **JAVA:** OpenJDK 11

**Comment by AndreyTu** [comment]
# Способ решения
Внесение изменений в код класса SavingAccountTest

# Шаги решения
1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom) в IDEA

2. Перейти в класс SavingAccount

3. Внести изменения в конструктор класса: 
```java
@Override
    public boolean pay(int amount) {
        if (amount <= 0) {
            return false;
        }
        if (balance - amount >= minBalance) {
            balance = balance - amount;
            return true;
        } else {
            return false;
        }
    }
```

5. Перейти в тестовый класс SavingAccountTest
6. Запустить с прежними данными тест shouldNotPayBeyondBalance



**Ожидаемый результат** : 1_000
**Фактический результат** : 1_000 (Process finished with exit code 0)
