### ISSUE TITLE
В процессе покупки при достижении минимального значения в методе pay(int amount) счет не уменьшается

### ISSUE THREAD

**Issue by Sergey30ssw** [AndreyTu/javaqa-team-diplom-2#7]
**Описание**
В методе pay(int amount) класса SavingAccount обнаружена ошибка в логике, которая приводит к отсутствию уменьшения баланса при покупке, когда баланс достигает минимального значения.

**Локация дефекта**
https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L49

 if (balance > minBalance) { 

**Шаги воспроизведения**
1. Создать экземпляр класса `SavingAccount` с начальным балансом `5_000`, минимальным балансом `1_000`, максимальным балансом `10_000` и ставкой `5`.
2. Вызвать метод `pay(int amount)` с заданной суммой покупки `4_000`.
3. Проверить результат уменьшения счета и значение баланса счета.

_Ожидаемый результат:_ метод `pay` должен вернуть `true`, баланс счета должен уменьшиться, став равным `1_000
`.

_Фактический результат:_ метод `pay` возвращает `false`, что указывает на неуспешное выполнение операции, баланс счета остался без изменений, равный `5_000`.

Тест
@Test
    public void shouldPayEqualsMinBalance() {
        SavingAccount account = new SavingAccount(
                5_000,
                1_000,
                10_000,
                5
        );

        boolean result = account.pay(4_000);

        Assertions.assertTrue(result);
        Assertions.assertEquals(5_000 - 4_000, account.getBalance());
    }

**Скриншот:**
![image](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/133129423/a1955635-c563-48c8-a37c-60258f9dd329)

**Окружение:**

- **Операционная система:** Windows 10 Pro v. 21H2
- **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
- **JAVA:** OpenJDK 11

**Comment by AndreyTu** [comment]
# Способ решения
Внесение изменений в код класса SavingAccount

# Шаги решения
1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom) в IDEA

2. Перейти в класс SavingAccount

3. Внести изменения в метод: pay

```java
@Override
    public boolean pay(int amount) {
        if (amount <= 0) {
            return false;
        }
        if (balance - amount >= minBalance) {
            balance = balance - amount;
            return true;
        } else {
            return false;
        }
    }
```

5. Перейти в тестовый класс SavingAccountTest
6. Запустить с прежними данными тест: shouldPayEqualsMinBalance

![Screenshot_3](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/139591226/e8fdb593-09cf-4366-987c-a6018c47b398)


**Ожидаемый результат** : Balance  1_000
**Фактический результат** : Balance   1_000 Process finished with exit code 0
