### ISSUE TITLE
Не выбрасывается исключение при параметрах SavingAccount конструктора MinBalance > MaxBalance

### ISSUE THREAD

**Issue by Sergey30ssw** [AndreyTu/javaqa-team-diplom-2#8]
**Описание**
При создании объекта класса SavingAccount с некорректными параметрами, где минимальный баланс больше максимального, не выбрасывается исключение IllegalArgumentException, хотя по логике требуется, чтобы такие параметры вызывали исключение.

**Локация дефекта**
https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java)a#L22-L32

 public SavingAccount(int initialBalance, int minBalance, int maxBalance, int rate) { 
     if (rate < 0) { 
         throw new IllegalArgumentException( 
           "Накопительная ставка не может быть отрицательной, а у вас: " + rate 
         ); 
     } 
     this.balance = initialBalance; 
     this.minBalance = minBalance; 
     this.maxBalance = maxBalance; 
     this.rate = rate; 
 } 
**Шаги воспроизведения:**
1. Попытаться создать объект класса `SavingAccount` с параметрами: `initialBalance = 5_000`, minBalance = 2_000, `maxBalance = 1_000`, `rate = 5`.

_Ожидаемый результат:_ при создании объекта должно выдаваться исключение `IllegalArgumentException` с соответствующим сообщением о некорректных параметрах.

_Фактический результат:_ исключение `IllegalArgumentException` не выдается, и объект создается без ошибок.

Тест
 @Test
    public void testIllegalArgumentExceptionMinBalanceMoreMaxBalance (){
        Assertions.assertThrows(IllegalArgumentException.class, () -> new SavingAccount(5_000,2_000,1_000,5));
    }

**Скриншот**
![image](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/133129423/5af40031-742f-4c4c-b2be-7525ab36ddd9)

**Окружение**

- **Операционная система:** Windows 10 Pro v. 21H2
- **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
- **JAVA:** OpenJDK 11

**Comment by AndreyTu** [comment]
# Способ решения
Внесение изменений в код класса SavingAccount

# Шаги решения
1. Открыть [код программы](https://github.com/AndreyTu/javaqa-team-diplom-2/blob/main/src/main/java/ru/netology/javaqadiplom) в IDEA

2. Перейти в класс SavingAccount

3. Внести изменения в метод: SavingAccount

```java
if (minBalance < 0) {
            throw new IllegalArgumentException(
                    "Минимальный баланс не может быть отрицательной, а у вас: " + minBalance
            );
        }
        if (initialBalance < 0) {
            throw new IllegalArgumentException(
                    "Первоначальный баланс не может быть меньше нуля, а у вас: " + initialBalance
            );
        }
        if ((initialBalance < minBalance) || (initialBalance > maxBalance)) {
            throw new IllegalArgumentException(
                    "Первоначальный баланс должен быть в пределах от минимального до максимального значения включительно, а у вас: " + initialBalance
            );
        }
        if (minBalance > maxBalance) {
            throw new IllegalArgumentException(
                    "Минимальный баланс не может быть больше максимального баланса, а у вас: " + minBalance
            );
        }

        this.balance = initialBalance;
        this.minBalance = minBalance;
        this.maxBalance = maxBalance;
        this.rate = rate;
    }
```

5. Перейти в тестовый класс SavingAccountTest
6. Запустить с прежними данными тест: testIllegalArgumentExceptionMinBalanceMoreMaxBalance

![Screenshot_4](https://github.com/AndreyTu/javaqa-team-diplom-2/assets/139591226/36927e59-e725-42e6-ab5f-4b7fd8abd43f)


**Ожидаемый результат** : при создании объекта должно выдаваться исключение IllegalArgumentException с соответствующим сообщением о некорректных параметрах.
**Фактический результат** : Тест проходит успешно Process finished with exit code 0
